/* 
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 6.12.0.20200605.001
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Currency conversion. Abstract class, do not use this class directly, use one of its children: Dcc, DynamicPricing.
    /// </summary>
    [DataContract]
    [JsonConverter(typeof(JsonSubtypes), "conversionType")]
    [JsonSubtypes.KnownSubType(typeof(DynamicPricing), "DynamicPricing")]
    [JsonSubtypes.KnownSubType(typeof(Dcc), "Dcc")]
    public partial class CurrencyConversion :  IEquatable<CurrencyConversion>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CurrencyConversion" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CurrencyConversion() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CurrencyConversion" /> class.
        /// </summary>
        /// <param name="conversionType">Type of currency conversion. (required).</param>
        /// <param name="inquiryRateId">Inquiry rate id. (required).</param>
        public CurrencyConversion(string conversionType = default(string), string inquiryRateId = default(string))
        {
            // to ensure "conversionType" is required (not null)
            if (conversionType == null)
            {
                throw new InvalidDataException("conversionType is a required property for CurrencyConversion and cannot be null");
            }
            else
            {
                this.ConversionType = conversionType;
            }
            
            // to ensure "inquiryRateId" is required (not null)
            if (inquiryRateId == null)
            {
                throw new InvalidDataException("inquiryRateId is a required property for CurrencyConversion and cannot be null");
            }
            else
            {
                this.InquiryRateId = inquiryRateId;
            }
            
        }
        
        /// <summary>
        /// Type of currency conversion.
        /// </summary>
        /// <value>Type of currency conversion.</value>
        [DataMember(Name="conversionType", EmitDefaultValue=true)]
        public string ConversionType { get; set; }

        /// <summary>
        /// Inquiry rate id.
        /// </summary>
        /// <value>Inquiry rate id.</value>
        [DataMember(Name="inquiryRateId", EmitDefaultValue=true)]
        public string InquiryRateId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CurrencyConversion {\n");
            sb.Append("  ConversionType: ").Append(ConversionType).Append("\n");
            sb.Append("  InquiryRateId: ").Append(InquiryRateId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CurrencyConversion);
        }

        /// <summary>
        /// Returns true if CurrencyConversion instances are equal
        /// </summary>
        /// <param name="input">Instance of CurrencyConversion to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CurrencyConversion input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ConversionType == input.ConversionType ||
                    (this.ConversionType != null &&
                    this.ConversionType.Equals(input.ConversionType))
                ) && 
                (
                    this.InquiryRateId == input.InquiryRateId ||
                    (this.InquiryRateId != null &&
                    this.InquiryRateId.Equals(input.InquiryRateId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ConversionType != null)
                    hashCode = hashCode * 59 + this.ConversionType.GetHashCode();
                if (this.InquiryRateId != null)
                    hashCode = hashCode * 59 + this.InquiryRateId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {

            
            // InquiryRateId (string) pattern
            Regex regexInquiryRateId = new Regex(@"^(?!\\s*$).+", RegexOptions.CultureInvariant);
            if (false == regexInquiryRateId.Match(this.InquiryRateId).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for InquiryRateId, must match a pattern of " + regexInquiryRateId, new [] { "InquiryRateId" });
            }

            yield break;
        }
    }

}
