/* 
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 6.14.0.20201015.001
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PaymentUrlDetailResponseAllOf
    /// </summary>
    [DataContract]
    public partial class PaymentUrlDetailResponseAllOf : IEquatable<PaymentUrlDetailResponseAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentUrlDetailResponseAllOf" /> class.
        /// </summary>
        /// <param name="paymentUrlDetails">Array of payment URL details..</param>
        public PaymentUrlDetailResponseAllOf(List<PaymentUrlDetail> paymentUrlDetails = default(List<PaymentUrlDetail>))
        {
            this.PaymentUrlDetails = paymentUrlDetails;
        }

        /// <summary>
        /// Array of payment URL details.
        /// </summary>
        /// <value>Array of payment URL details.</value>
        [DataMember(Name = "paymentUrlDetails", EmitDefaultValue = false)]
        public List<PaymentUrlDetail> PaymentUrlDetails { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentUrlDetailResponseAllOf {\n");
            sb.Append("  PaymentUrlDetails: ").Append(PaymentUrlDetails).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PaymentUrlDetailResponseAllOf);
        }

        /// <summary>
        /// Returns true if PaymentUrlDetailResponseAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of PaymentUrlDetailResponseAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentUrlDetailResponseAllOf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PaymentUrlDetails == input.PaymentUrlDetails ||
                    this.PaymentUrlDetails != null &&
                    input.PaymentUrlDetails != null &&
                    this.PaymentUrlDetails.SequenceEqual(input.PaymentUrlDetails)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PaymentUrlDetails != null)
                    hashCode = hashCode * 59 + this.PaymentUrlDetails.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
