/*
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 21.5.0.20211029.001
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Payment method containing payment card information.
    /// </summary>
    [DataContract(Name = "PaymentCardPaymentMethod")]
    public partial class PaymentCardPaymentMethod : IEquatable<PaymentCardPaymentMethod>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentCardPaymentMethod" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PaymentCardPaymentMethod() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentCardPaymentMethod" /> class.
        /// </summary>
        /// <param name="paymentCard">paymentCard (required).</param>
        /// <param name="paymentFacilitator">paymentFacilitator.</param>
        public PaymentCardPaymentMethod(PaymentCard paymentCard = default(PaymentCard), PaymentFacilitator paymentFacilitator = default(PaymentFacilitator))
        {
            // to ensure "paymentCard" is required (not null)
            this.PaymentCard = paymentCard ?? throw new ArgumentNullException("paymentCard is a required property for PaymentCardPaymentMethod and cannot be null");
            this.PaymentFacilitator = paymentFacilitator;
        }

        /// <summary>
        /// Gets or Sets PaymentCard
        /// </summary>
        [DataMember(Name = "paymentCard", IsRequired = true, EmitDefaultValue = false)]
        public PaymentCard PaymentCard { get; set; }

        /// <summary>
        /// Gets or Sets PaymentFacilitator
        /// </summary>
        [DataMember(Name = "paymentFacilitator", EmitDefaultValue = false)]
        public PaymentFacilitator PaymentFacilitator { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentCardPaymentMethod {\n");
            sb.Append("  PaymentCard: ").Append(PaymentCard).Append("\n");
            sb.Append("  PaymentFacilitator: ").Append(PaymentFacilitator).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PaymentCardPaymentMethod);
        }

        /// <summary>
        /// Returns true if PaymentCardPaymentMethod instances are equal
        /// </summary>
        /// <param name="input">Instance of PaymentCardPaymentMethod to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentCardPaymentMethod input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PaymentCard == input.PaymentCard ||
                    (this.PaymentCard != null &&
                    this.PaymentCard.Equals(input.PaymentCard))
                ) && 
                (
                    this.PaymentFacilitator == input.PaymentFacilitator ||
                    (this.PaymentFacilitator != null &&
                    this.PaymentFacilitator.Equals(input.PaymentFacilitator))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PaymentCard != null)
                    hashCode = hashCode * 59 + this.PaymentCard.GetHashCode();
                if (this.PaymentFacilitator != null)
                    hashCode = hashCode * 59 + this.PaymentFacilitator.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
