/* 
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 21.2.0.20210406.001
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing AccessTokenResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccessTokenResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccessTokenResponse
        //private AccessTokenResponse instance;

        public AccessTokenResponseTests()
        {
            // TODO uncomment below to create an instance of AccessTokenResponse
            //instance = new AccessTokenResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccessTokenResponse
        /// </summary>
        [Fact]
        public void AccessTokenResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccessTokenResponse
            //Assert.IsInstanceOfType<AccessTokenResponse> (instance, "variable 'instance' is a AccessTokenResponse");
        }


        /// <summary>
        /// Test the property 'TokenId'
        /// </summary>
        [Fact]
        public void TokenIdTest()
        {
            // TODO unit test for the property 'TokenId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'IssuedOn'
        /// </summary>
        [Fact]
        public void IssuedOnTest()
        {
            // TODO unit test for the property 'IssuedOn'
        }
        /// <summary>
        /// Test the property 'ExpiresInSeconds'
        /// </summary>
        [Fact]
        public void ExpiresInSecondsTest()
        {
            // TODO unit test for the property 'ExpiresInSeconds'
        }
        /// <summary>
        /// Test the property 'PublicKeyBase64'
        /// </summary>
        [Fact]
        public void PublicKeyBase64Test()
        {
            // TODO unit test for the property 'PublicKeyBase64'
        }
        /// <summary>
        /// Test the property 'Algorithm'
        /// </summary>
        [Fact]
        public void AlgorithmTest()
        {
            // TODO unit test for the property 'Algorithm'
        }
        /// <summary>
        /// Test the property 'ClientRequestId'
        /// </summary>
        [Fact]
        public void ClientRequestIdTest()
        {
            // TODO unit test for the property 'ClientRequestId'
        }

    }

}
