/* 
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 21.3.0.20210608.001
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing AdditionalTransactionDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdditionalTransactionDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdditionalTransactionDetails
        //private AdditionalTransactionDetails instance;

        public AdditionalTransactionDetailsTests()
        {
            // TODO uncomment below to create an instance of AdditionalTransactionDetails
            //instance = new AdditionalTransactionDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdditionalTransactionDetails
        /// </summary>
        [Fact]
        public void AdditionalTransactionDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AdditionalTransactionDetails
            //Assert.IsInstanceOfType<AdditionalTransactionDetails> (instance, "variable 'instance' is a AdditionalTransactionDetails");
        }


        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Fact]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'InvoiceNumber'
        /// </summary>
        [Fact]
        public void InvoiceNumberTest()
        {
            // TODO unit test for the property 'InvoiceNumber'
        }
        /// <summary>
        /// Test the property 'PurchaseOrderNumber'
        /// </summary>
        [Fact]
        public void PurchaseOrderNumberTest()
        {
            // TODO unit test for the property 'PurchaseOrderNumber'
        }
        /// <summary>
        /// Test the property 'DisbursementTransType'
        /// </summary>
        [Fact]
        public void DisbursementTransTypeTest()
        {
            // TODO unit test for the property 'DisbursementTransType'
        }
        /// <summary>
        /// Test the property 'WalletProvider'
        /// </summary>
        [Fact]
        public void WalletProviderTest()
        {
            // TODO unit test for the property 'WalletProvider'
        }
        /// <summary>
        /// Test the property 'Receipts'
        /// </summary>
        [Fact]
        public void ReceiptsTest()
        {
            // TODO unit test for the property 'Receipts'
        }

    }

}
