/* 
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 21.1.0.20210122.001
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing AirlineTravelRoute
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AirlineTravelRouteTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AirlineTravelRoute
        //private AirlineTravelRoute instance;

        public AirlineTravelRouteTests()
        {
            // TODO uncomment below to create an instance of AirlineTravelRoute
            //instance = new AirlineTravelRoute();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AirlineTravelRoute
        /// </summary>
        [Fact]
        public void AirlineTravelRouteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AirlineTravelRoute
            //Assert.IsInstanceOfType<AirlineTravelRoute> (instance, "variable 'instance' is a AirlineTravelRoute");
        }


        /// <summary>
        /// Test the property 'DepartureDate'
        /// </summary>
        [Fact]
        public void DepartureDateTest()
        {
            // TODO unit test for the property 'DepartureDate'
        }
        /// <summary>
        /// Test the property 'Origin'
        /// </summary>
        [Fact]
        public void OriginTest()
        {
            // TODO unit test for the property 'Origin'
        }
        /// <summary>
        /// Test the property 'Destination'
        /// </summary>
        [Fact]
        public void DestinationTest()
        {
            // TODO unit test for the property 'Destination'
        }
        /// <summary>
        /// Test the property 'CarrierCode'
        /// </summary>
        [Fact]
        public void CarrierCodeTest()
        {
            // TODO unit test for the property 'CarrierCode'
        }
        /// <summary>
        /// Test the property 'ServiceClass'
        /// </summary>
        [Fact]
        public void ServiceClassTest()
        {
            // TODO unit test for the property 'ServiceClass'
        }
        /// <summary>
        /// Test the property 'StopoverType'
        /// </summary>
        [Fact]
        public void StopoverTypeTest()
        {
            // TODO unit test for the property 'StopoverType'
        }
        /// <summary>
        /// Test the property 'FareBasisCode'
        /// </summary>
        [Fact]
        public void FareBasisCodeTest()
        {
            // TODO unit test for the property 'FareBasisCode'
        }
        /// <summary>
        /// Test the property 'DepartureTax'
        /// </summary>
        [Fact]
        public void DepartureTaxTest()
        {
            // TODO unit test for the property 'DepartureTax'
        }
        /// <summary>
        /// Test the property 'FlightNumber'
        /// </summary>
        [Fact]
        public void FlightNumberTest()
        {
            // TODO unit test for the property 'FlightNumber'
        }

    }

}
