/* 
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 21.1.0.20210122.001
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing AuthenticationResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuthenticationResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuthenticationResult
        //private AuthenticationResult instance;

        public AuthenticationResultTests()
        {
            // TODO uncomment below to create an instance of AuthenticationResult
            //instance = new AuthenticationResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuthenticationResult
        /// </summary>
        [Fact]
        public void AuthenticationResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AuthenticationResult
            //Assert.IsInstanceOfType<AuthenticationResult> (instance, "variable 'instance' is a AuthenticationResult");
        }

        /// <summary>
        /// Test deserialize a Secure3DAuthenticationResult from type AuthenticationResult
        /// </summary>
        [Fact]
        public void Secure3DAuthenticationResultDeserializeFromAuthenticationResultTest()
        {
            // TODO uncomment below to test deserialize a Secure3DAuthenticationResult from type AuthenticationResult
            //Assert.IsInstanceOf<AuthenticationResult>(JsonConvert.DeserializeObject<AuthenticationResult>(new Secure3DAuthenticationResult().ToJson()));
        }
        /// <summary>
        /// Test deserialize a Secure3D10AuthenticationResult from type AuthenticationResult
        /// </summary>
        [Fact]
        public void Secure3D10AuthenticationResultDeserializeFromAuthenticationResultTest()
        {
            // TODO uncomment below to test deserialize a Secure3D10AuthenticationResult from type AuthenticationResult
            //Assert.IsInstanceOf<AuthenticationResult>(JsonConvert.DeserializeObject<AuthenticationResult>(new Secure3D10AuthenticationResult().ToJson()));
        }
        /// <summary>
        /// Test deserialize a Secure3D21AuthenticationResult from type AuthenticationResult
        /// </summary>
        [Fact]
        public void Secure3D21AuthenticationResultDeserializeFromAuthenticationResultTest()
        {
            // TODO uncomment below to test deserialize a Secure3D21AuthenticationResult from type AuthenticationResult
            //Assert.IsInstanceOf<AuthenticationResult>(JsonConvert.DeserializeObject<AuthenticationResult>(new Secure3D21AuthenticationResult().ToJson()));
        }

        /// <summary>
        /// Test the property 'AuthenticationType'
        /// </summary>
        [Fact]
        public void AuthenticationTypeTest()
        {
            // TODO unit test for the property 'AuthenticationType'
        }

    }

}
