/* 
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 6.6.0.20190507.002
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CardVerificationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CardVerificationRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CardVerificationRequest
        //private CardVerificationRequest instance;

        public CardVerificationRequestTests()
        {
            // TODO uncomment below to create an instance of CardVerificationRequest
            //instance = new CardVerificationRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CardVerificationRequest
        /// </summary>
        [Fact]
        public void CardVerificationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CardVerificationRequest
            //Assert.IsInstanceOfType<CardVerificationRequest> (instance, "variable 'instance' is a CardVerificationRequest");
        }


        /// <summary>
        /// Test the property 'PaymentCard'
        /// </summary>
        [Fact]
        public void PaymentCardTest()
        {
            // TODO unit test for the property 'PaymentCard'
        }
        /// <summary>
        /// Test the property 'BillingAddress'
        /// </summary>
        [Fact]
        public void BillingAddressTest()
        {
            // TODO unit test for the property 'BillingAddress'
        }
        /// <summary>
        /// Test the property 'StoreId'
        /// </summary>
        [Fact]
        public void StoreIdTest()
        {
            // TODO unit test for the property 'StoreId'
        }

    }

}
