/* 
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 6.6.0.20190507.002
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Device
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeviceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Device
        //private Device instance;

        public DeviceTests()
        {
            // TODO uncomment below to create an instance of Device
            //instance = new Device();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Device
        /// </summary>
        [Fact]
        public void DeviceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Device
            //Assert.IsInstanceOfType<Device> (instance, "variable 'instance' is a Device");
        }


        /// <summary>
        /// Test the property 'DeviceType'
        /// </summary>
        [Fact]
        public void DeviceTypeTest()
        {
            // TODO unit test for the property 'DeviceType'
        }
        /// <summary>
        /// Test the property 'DeviceId'
        /// </summary>
        [Fact]
        public void DeviceIdTest()
        {
            // TODO unit test for the property 'DeviceId'
        }
        /// <summary>
        /// Test the property 'Networks'
        /// </summary>
        [Fact]
        public void NetworksTest()
        {
            // TODO unit test for the property 'Networks'
        }
        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Fact]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }
        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Fact]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }
        /// <summary>
        /// Test the property 'Imei'
        /// </summary>
        [Fact]
        public void ImeiTest()
        {
            // TODO unit test for the property 'Imei'
        }
        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }
        /// <summary>
        /// Test the property 'Manufacturer'
        /// </summary>
        [Fact]
        public void ManufacturerTest()
        {
            // TODO unit test for the property 'Manufacturer'
        }
        /// <summary>
        /// Test the property 'TimezoneOffset'
        /// </summary>
        [Fact]
        public void TimezoneOffsetTest()
        {
            // TODO unit test for the property 'TimezoneOffset'
        }
        /// <summary>
        /// Test the property 'Rooted'
        /// </summary>
        [Fact]
        public void RootedTest()
        {
            // TODO unit test for the property 'Rooted'
        }
        /// <summary>
        /// Test the property 'MalwareDetected'
        /// </summary>
        [Fact]
        public void MalwareDetectedTest()
        {
            // TODO unit test for the property 'MalwareDetected'
        }
        /// <summary>
        /// Test the property 'UserDefined'
        /// </summary>
        [Fact]
        public void UserDefinedTest()
        {
            // TODO unit test for the property 'UserDefined'
        }

    }

}
