/* 
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 6.9.1.20191223.002
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PaymentTokenizationErrorResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentTokenizationErrorResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentTokenizationErrorResponse
        //private PaymentTokenizationErrorResponse instance;

        public PaymentTokenizationErrorResponseTests()
        {
            // TODO uncomment below to create an instance of PaymentTokenizationErrorResponse
            //instance = new PaymentTokenizationErrorResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentTokenizationErrorResponse
        /// </summary>
        [Fact]
        public void PaymentTokenizationErrorResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PaymentTokenizationErrorResponse
            //Assert.IsInstanceOfType<PaymentTokenizationErrorResponse> (instance, "variable 'instance' is a PaymentTokenizationErrorResponse");
        }


        /// <summary>
        /// Test the property 'ClientRequestId'
        /// </summary>
        [Fact]
        public void ClientRequestIdTest()
        {
            // TODO unit test for the property 'ClientRequestId'
        }
        /// <summary>
        /// Test the property 'ApiTraceId'
        /// </summary>
        [Fact]
        public void ApiTraceIdTest()
        {
            // TODO unit test for the property 'ApiTraceId'
        }
        /// <summary>
        /// Test the property 'ResponseType'
        /// </summary>
        [Fact]
        public void ResponseTypeTest()
        {
            // TODO unit test for the property 'ResponseType'
        }
        /// <summary>
        /// Test the property 'RequestStatus'
        /// </summary>
        [Fact]
        public void RequestStatusTest()
        {
            // TODO unit test for the property 'RequestStatus'
        }
        /// <summary>
        /// Test the property 'RequestTime'
        /// </summary>
        [Fact]
        public void RequestTimeTest()
        {
            // TODO unit test for the property 'RequestTime'
        }
        /// <summary>
        /// Test the property 'Brand'
        /// </summary>
        [Fact]
        public void BrandTest()
        {
            // TODO unit test for the property 'Brand'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'PaymentToken'
        /// </summary>
        [Fact]
        public void PaymentTokenTest()
        {
            // TODO unit test for the property 'PaymentToken'
        }
        /// <summary>
        /// Test the property 'PaymentCard'
        /// </summary>
        [Fact]
        public void PaymentCardTest()
        {
            // TODO unit test for the property 'PaymentCard'
        }
        /// <summary>
        /// Test the property 'Processor'
        /// </summary>
        [Fact]
        public void ProcessorTest()
        {
            // TODO unit test for the property 'Processor'
        }
        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Fact]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

    }

}
