/* 
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 6.10.1.20200226.002
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PaymentCardPreAuthTransaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentCardPreAuthTransactionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentCardPreAuthTransaction
        //private PaymentCardPreAuthTransaction instance;

        public PaymentCardPreAuthTransactionTests()
        {
            // TODO uncomment below to create an instance of PaymentCardPreAuthTransaction
            //instance = new PaymentCardPreAuthTransaction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentCardPreAuthTransaction
        /// </summary>
        [Fact]
        public void PaymentCardPreAuthTransactionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PaymentCardPreAuthTransaction
            //Assert.IsInstanceOfType<PaymentCardPreAuthTransaction> (instance, "variable 'instance' is a PaymentCardPreAuthTransaction");
        }


        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Fact]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'StoredCredentials'
        /// </summary>
        [Fact]
        public void StoredCredentialsTest()
        {
            // TODO unit test for the property 'StoredCredentials'
        }
        /// <summary>
        /// Test the property 'CreateToken'
        /// </summary>
        [Fact]
        public void CreateTokenTest()
        {
            // TODO unit test for the property 'CreateToken'
        }
        /// <summary>
        /// Test the property 'SplitShipment'
        /// </summary>
        [Fact]
        public void SplitShipmentTest()
        {
            // TODO unit test for the property 'SplitShipment'
        }
        /// <summary>
        /// Test the property 'SettlementSplit'
        /// </summary>
        [Fact]
        public void SettlementSplitTest()
        {
            // TODO unit test for the property 'SettlementSplit'
        }
        /// <summary>
        /// Test the property 'AuthenticationRequest'
        /// </summary>
        [Fact]
        public void AuthenticationRequestTest()
        {
            // TODO unit test for the property 'AuthenticationRequest'
        }
        /// <summary>
        /// Test the property 'AuthenticationResult'
        /// </summary>
        [Fact]
        public void AuthenticationResultTest()
        {
            // TODO unit test for the property 'AuthenticationResult'
        }

    }

}
