/* 
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 21.1.0.20210122.001
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PaymentTokenSaleTransactionAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentTokenSaleTransactionAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentTokenSaleTransactionAllOf
        //private PaymentTokenSaleTransactionAllOf instance;

        public PaymentTokenSaleTransactionAllOfTests()
        {
            // TODO uncomment below to create an instance of PaymentTokenSaleTransactionAllOf
            //instance = new PaymentTokenSaleTransactionAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentTokenSaleTransactionAllOf
        /// </summary>
        [Fact]
        public void PaymentTokenSaleTransactionAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PaymentTokenSaleTransactionAllOf
            //Assert.IsInstanceOfType<PaymentTokenSaleTransactionAllOf> (instance, "variable 'instance' is a PaymentTokenSaleTransactionAllOf");
        }


        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Fact]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'StoredCredentials'
        /// </summary>
        [Fact]
        public void StoredCredentialsTest()
        {
            // TODO unit test for the property 'StoredCredentials'
        }
        /// <summary>
        /// Test the property 'SettlementSplit'
        /// </summary>
        [Fact]
        public void SettlementSplitTest()
        {
            // TODO unit test for the property 'SettlementSplit'
        }
        /// <summary>
        /// Test the property 'CurrencyConversion'
        /// </summary>
        [Fact]
        public void CurrencyConversionTest()
        {
            // TODO unit test for the property 'CurrencyConversion'
        }
        /// <summary>
        /// Test the property 'AuthenticationRequest'
        /// </summary>
        [Fact]
        public void AuthenticationRequestTest()
        {
            // TODO unit test for the property 'AuthenticationRequest'
        }
        /// <summary>
        /// Test the property 'AuthenticationResult'
        /// </summary>
        [Fact]
        public void AuthenticationResultTest()
        {
            // TODO unit test for the property 'AuthenticationResult'
        }

    }

}
