/* 
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 6.9.1.20191223.002
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing PaymentDeviceDisbursementTransaction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentDeviceDisbursementTransactionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentDeviceDisbursementTransaction
        //private PaymentDeviceDisbursementTransaction instance;

        public PaymentDeviceDisbursementTransactionTests()
        {
            // TODO uncomment below to create an instance of PaymentDeviceDisbursementTransaction
            //instance = new PaymentDeviceDisbursementTransaction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentDeviceDisbursementTransaction
        /// </summary>
        [Fact]
        public void PaymentDeviceDisbursementTransactionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PaymentDeviceDisbursementTransaction
            //Assert.IsInstanceOfType<PaymentDeviceDisbursementTransaction> (instance, "variable 'instance' is a PaymentDeviceDisbursementTransaction");
        }


        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Fact]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'Disbursement'
        /// </summary>
        [Fact]
        public void DisbursementTest()
        {
            // TODO unit test for the property 'Disbursement'
        }

    }

}
