/* 
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 21.3.0.20210608.001
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ProvideDetailPaymentStepRequestAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProvideDetailPaymentStepRequestAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProvideDetailPaymentStepRequestAllOf
        //private ProvideDetailPaymentStepRequestAllOf instance;

        public ProvideDetailPaymentStepRequestAllOfTests()
        {
            // TODO uncomment below to create an instance of ProvideDetailPaymentStepRequestAllOf
            //instance = new ProvideDetailPaymentStepRequestAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProvideDetailPaymentStepRequestAllOf
        /// </summary>
        [Fact]
        public void ProvideDetailPaymentStepRequestAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProvideDetailPaymentStepRequestAllOf
            //Assert.IsInstanceOfType<ProvideDetailPaymentStepRequestAllOf> (instance, "variable 'instance' is a ProvideDetailPaymentStepRequestAllOf");
        }


        /// <summary>
        /// Test the property 'Hint'
        /// </summary>
        [Fact]
        public void HintTest()
        {
            // TODO unit test for the property 'Hint'
        }
        /// <summary>
        /// Test the property 'JavaScriptValidationExpression'
        /// </summary>
        [Fact]
        public void JavaScriptValidationExpressionTest()
        {
            // TODO unit test for the property 'JavaScriptValidationExpression'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

    }

}
