/* 
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 6.8.0.20190731.002
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing ResponseType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ResponseTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ResponseType
        //private ResponseType instance;

        public ResponseTypeTests()
        {
            // TODO uncomment below to create an instance of ResponseType
            //instance = new ResponseType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ResponseType
        /// </summary>
        [Fact]
        public void ResponseTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ResponseType
            //Assert.IsInstanceOfType<ResponseType> (instance, "variable 'instance' is a ResponseType");
        }



    }

}
