/* 
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 21.1.0.20210122.001
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Secure3DAuthenticationResponseSecure3dMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Secure3DAuthenticationResponseSecure3dMethodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Secure3DAuthenticationResponseSecure3dMethod
        //private Secure3DAuthenticationResponseSecure3dMethod instance;

        public Secure3DAuthenticationResponseSecure3dMethodTests()
        {
            // TODO uncomment below to create an instance of Secure3DAuthenticationResponseSecure3dMethod
            //instance = new Secure3DAuthenticationResponseSecure3dMethod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Secure3DAuthenticationResponseSecure3dMethod
        /// </summary>
        [Fact]
        public void Secure3DAuthenticationResponseSecure3dMethodInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Secure3DAuthenticationResponseSecure3dMethod
            //Assert.IsInstanceOfType<Secure3DAuthenticationResponseSecure3dMethod> (instance, "variable 'instance' is a Secure3DAuthenticationResponseSecure3dMethod");
        }


        /// <summary>
        /// Test the property 'MethodForm'
        /// </summary>
        [Fact]
        public void MethodFormTest()
        {
            // TODO unit test for the property 'MethodForm'
        }
        /// <summary>
        /// Test the property 'Secure3dTransId'
        /// </summary>
        [Fact]
        public void Secure3dTransIdTest()
        {
            // TODO unit test for the property 'Secure3dTransId'
        }

    }

}
