/* 
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 21.3.0.20210608.001
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing StandInDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StandInDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StandInDetails
        //private StandInDetails instance;

        public StandInDetailsTests()
        {
            // TODO uncomment below to create an instance of StandInDetails
            //instance = new StandInDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StandInDetails
        /// </summary>
        [Fact]
        public void StandInDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StandInDetails
            //Assert.IsInstanceOfType<StandInDetails> (instance, "variable 'instance' is a StandInDetails");
        }


        /// <summary>
        /// Test the property 'StandInType'
        /// </summary>
        [Fact]
        public void StandInTypeTest()
        {
            // TODO unit test for the property 'StandInType'
        }
        /// <summary>
        /// Test the property 'NumberOfDebits'
        /// </summary>
        [Fact]
        public void NumberOfDebitsTest()
        {
            // TODO unit test for the property 'NumberOfDebits'
        }
        /// <summary>
        /// Test the property 'SiValidated'
        /// </summary>
        [Fact]
        public void SiValidatedTest()
        {
            // TODO unit test for the property 'SiValidated'
        }
        /// <summary>
        /// Test the property 'MaximumTransactionAmount'
        /// </summary>
        [Fact]
        public void MaximumTransactionAmountTest()
        {
            // TODO unit test for the property 'MaximumTransactionAmount'
        }
        /// <summary>
        /// Test the property 'SiHubId'
        /// </summary>
        [Fact]
        public void SiHubIdTest()
        {
            // TODO unit test for the property 'SiHubId'
        }
        /// <summary>
        /// Test the property 'Frequency'
        /// </summary>
        [Fact]
        public void FrequencyTest()
        {
            // TODO unit test for the property 'Frequency'
        }

    }

}
