/* 
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 6.10.1.20200226.002
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing UpdateFraudSettingsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateFraudSettingsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateFraudSettingsResponse
        //private UpdateFraudSettingsResponse instance;

        public UpdateFraudSettingsResponseTests()
        {
            // TODO uncomment below to create an instance of UpdateFraudSettingsResponse
            //instance = new UpdateFraudSettingsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateFraudSettingsResponse
        /// </summary>
        [Fact]
        public void UpdateFraudSettingsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateFraudSettingsResponse
            //Assert.IsInstanceOfType<UpdateFraudSettingsResponse> (instance, "variable 'instance' is a UpdateFraudSettingsResponse");
        }


        /// <summary>
        /// Test the property 'ClientRequestId'
        /// </summary>
        [Fact]
        public void ClientRequestIdTest()
        {
            // TODO unit test for the property 'ClientRequestId'
        }
        /// <summary>
        /// Test the property 'ApiTraceId'
        /// </summary>
        [Fact]
        public void ApiTraceIdTest()
        {
            // TODO unit test for the property 'ApiTraceId'
        }
        /// <summary>
        /// Test the property 'ResponseType'
        /// </summary>
        [Fact]
        public void ResponseTypeTest()
        {
            // TODO unit test for the property 'ResponseType'
        }
        /// <summary>
        /// Test the property 'Stores'
        /// </summary>
        [Fact]
        public void StoresTest()
        {
            // TODO unit test for the property 'Stores'
        }

    }

}
