/* 
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 6.9.1.20191223.002
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing UpdateFraudSettingsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateFraudSettingsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateFraudSettingsRequest
        //private UpdateFraudSettingsRequest instance;

        public UpdateFraudSettingsRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateFraudSettingsRequest
            //instance = new UpdateFraudSettingsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateFraudSettingsRequest
        /// </summary>
        [Fact]
        public void UpdateFraudSettingsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UpdateFraudSettingsRequest
            //Assert.IsInstanceOfType<UpdateFraudSettingsRequest> (instance, "variable 'instance' is a UpdateFraudSettingsRequest");
        }


        /// <summary>
        /// Test the property 'Stores'
        /// </summary>
        [Fact]
        public void StoresTest()
        {
            // TODO unit test for the property 'Stores'
        }

    }

}
